logging:
  level:
    root: info
    com:
      kgignatyev: debug

ladder:
  simulate-errors: false


spring:
  #  cache:
  #    jcache:
  #     config: "classpath:ehcache.xml"

  jmx:
    enabled: false

  mvc:
    throw-exception-if-no-handler-found: true


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/public/mgmt
    health:
      sensitive: false
  simple:
    metrics:
      export:
        enabled: true



